---
title: "Homework 4 - Sorting"
author: "Nicolas Solomita"
date: "31/3/2020"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exercise 3

__Argue about the following statement and answer the questions__
  
1. Heap Sort on a array A whose length is $n$ takes time $O(n)$.
2. Heap Sort on a array A whose length is $n$ takes time $\Omega(n)$.
3. What is the worst case complexity for Heap Sort?
4. Quick Sort on a array A whose length is $n$ takes time $O(n^3)$.
5. What is the complexity of Quick Sort?
6. Bubble Sort on a array A whose length is $n$ takes time $\Omega(n)$. 
7. What is the complexity of Bubble Sort?

__Solution__

1. FALSE: the complexity of Heap Sort is $O(n \log n)$.

2. TRUE: The procedure calls $n$ times Heapify, whose cost is $O(\log n)$. However, if we have a particular case (an already sorted array A), Heapify will cost $\Theta(1)$. Therefore, we can fix the complexity of Heap Sort at $\Omega(n)$.

3. The worst case complexity is $\Theta(n \log n)$.

4. FALSE: the complexity of Quick Sort in the worst case is $\Theta(n^2)$.

5. The complexity of Quick Sort in the worst case is $\Theta(n^2)$, while in the avg and in the best case is $\Theta(n \log n)$.

6. TRUE: in the best case (the array A already ordered) the algorithm does only $n-1$ comparisons. Therefore it costs $\Omega(n)$
  
7. The complexity of Bubble Sort is $O(n^2)$.

### Exercise 4
Solve the following recursive equation:
$$
\begin{equation}
  T(n)=\begin{cases}
    \Theta(1) & \text{if $n=32$}\\
    3*T(\frac{n}{4}) + \Theta(n^{\frac{3}{2}}) & \text{otherwise}
  \end{cases}
\end{equation}
$$

At the i-th step of the recursion tree there are $3^i$ recursive calls, each one taking time $c\Big(\frac{n}{4^i}\Big)^\frac{3}{2}$. 

The base case is $n=32$, therefore the size of the subproblem at the last level is:
$$
\frac{n}{4^i} = 32
$$
the height of the tree is:
$$
i = \frac{1}{2}log_2 n -5
$$
and the number of nodes in the last level is:
$$
3^{\frac{1}{2}log_2 n -5}
$$

Now, we can compute the total complexity, with $k=\frac{1}{2}(log_2 n -5)$:
$$
\begin{align}
T(n) &= \sum_{i=0}^{k-1} 3^ic\Big(\frac{n}{4^i}\Big)^\frac{3}{2} + \Theta(3^k) =
\\ &= cn^{\frac{3}{2}} \sum_{i=0}^{k-1} \Big(\frac{3}{8}\Big)^i + \Theta(3^k) \leq
\\ &\leq cn^{\frac{3}{2}} \sum_{i=0}^\infty \Big(\frac{3}{8}\Big)^i + \Theta(3^k) =
\\ &= cn^{\frac{3}{2}} \frac{1}{1-\frac{3}{8}} + \Theta(3^k) =
\\ &= \frac{8}{5}cn^{\frac{3}{2}} + \Theta(3^k)
\end{align}
$$
We can conclude that $T(n) \in O(n^\frac{3}{2})$.
